name: Deploy Terraform on Azure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.15.0 # Use the desired Terraform version

      - name: Initialize Terraform
        run: terraform init

      - name: Deploy Terraform
        run: terraform plan
        # run: terraform apply -auto-approve

