name: Terraform Security Scan

on:
  push: {}

jobs:
  tfsec_scan:
    name: Run tfsec
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Install tfsec
      run: go get -u github.com/tfsec/tfsec/cmd/tfsec

    - name: Run tfsec
      run: tfsec .
     
